# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-24 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='Product_color',
            new_name='product_color',
        ),
    ]
